# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        docker run --rm -v "$(pwd):/app:rw" ubuntu:lunar bash -c ' \
        apt update -y && apt install -y software-properties-common && \
        apt-add-repository ppa:launchpad/ubuntu/ppa && \
        apt update -y && \
        apt-get install -y --no-install-recommends curl apt-utils build-essential sudo git libgtk-4-dev libadwaita-1-dev=1.2.0-1ubuntu2 && \
        curl -OL https://go.dev/dl/go1.21.6.linux-amd64.tar.gz && \
        tar xf go1.21.6.linux-amd64.tar.gz && \
        export PATH="${PATH}:$(pwd)/go/bin" && \
        go env && \
        ./dist.sh build \
        '

    # Create release
    - name: Generate release tag
      id: tag
      run: |
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh
        sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
        echo "release_tag=ActionBuild_$(date +"%Y.%m.%d_%H-%M-%S")" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          ./trayscale*
    # Done release

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
